apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qxwn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yypp-tenant/rhtap-demo-app/hacbs-test-project-qxwn@sha256:b972d3eb9858a2081f373374fd46b62c9f0ab9454ad29829f02db83d6e814438
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
