apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qxwn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qxwn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qxwn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qxwn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qxwn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yypp-tenant/rhtap-demo-app/hacbs-test-project-qxwn@sha256:b972d3eb9858a2081f373374fd46b62c9f0ab9454ad29829f02db83d6e814438
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
